name: Build and Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch: # 支持手动触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 🛠️ Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 🛠️ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: 📦 Install Dependencies
        run: pnpm install

      - name: 🏗️ Build data
        run: bun build:data

      - name: 🏗️ Build web
        run: bun build:web

      - name: 🏗️ Build singlefile web
        run: bun build:singleweb

      - name: 🚀 Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: apps/web/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5